name: Copy cloud-docs for TFE
description: Copy docs/nav-data/assets from source dir to target dir
runs:
  using: 'node20'
  main: 'out/index.js'
inputs:
  source_dir:
    required: true
    description: 'The absolute path from which to copy files. Ex: /home/runner/work/mktg-content-workflows/mktg-content-workflows/cloud-docs'
  target_dir:
    required: true
    description: 'The absolute path to which to copy files. Ex: /home/runner/work/mktg-content-workflows/mktg-content-workflows/ptfe-releases'
