name: Copy cloud-docs for TFE
description: Copy docs/nav-data/assets from source repo to target repo
runs:
  using: 'node20'
  main: 'out/index.js'
inputs:
  source_repo:
    required: true
    description: 'The absolute path to a GitHub repository root, on disk. Ex: /home/runner/work/mktg-content-workflows/mktg-content-workflows/terraform-docs-common'
  target_repo:
    description: 'The absolute path to a GitHub repository root, on disk. Ex: /home/runner/work/mktg-content-workflows/mktg-content-workflows/ptfe-releases'
    required: true
