name: Copy cloud-docs for TFE
description: Copy docs/nav-data/assets from source dir to target dir
runs:
  using: 'node20'
  main: 'out/index.js'
inputs:
  new_TFE_version:
    required: true
    description: 'The new TFE version to create and copy docs into.'
