name: Check Prebuild Binaries

on:
  pull_request:
    paths:
      - 'scripts/prebuild/**'
  push:
    branches:
      - main
    paths:
      - 'scripts/prebuild/**'

jobs:
  check-prebuild-binaries:
    runs-on: ubuntu-latest
    name: Validate prebuild binaries are updated

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to compare changes

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            scripts/prebuild/**
          files_ignore: |
            scripts/prebuild/prebuild-arm-mac-binary
            scripts/prebuild/prebuild-x64-linux-binary

      - name: Check if prebuild scripts changed
        id: check-changes
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]]; then
            echo "prebuild_changed=true" >> $GITHUB_OUTPUT
            echo "✅ Prebuild scripts have changed"
          else
            echo "prebuild_changed=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No prebuild script changes detected"
          fi

      - name: Check if binaries were updated
        id: check-binaries
        if: steps.check-changes.outputs.prebuild_changed == 'true'
        uses: tj-actions/changed-files@v44
        with:
          files: |
            scripts/prebuild/prebuild-arm-mac-binary
            scripts/prebuild/prebuild-x64-linux-binary

      - name: Validate binary updates
        if: steps.check-changes.outputs.prebuild_changed == 'true'
        run: |
          echo "Prebuild scripts changed: ${{ steps.check-changes.outputs.prebuild_changed }}"
          echo "Binaries changed: ${{ steps.check-binaries.outputs.any_changed }}"
          echo "Changed binaries: ${{ steps.check-binaries.outputs.all_changed_files }}"

          if [[ "${{ steps.check-binaries.outputs.any_changed }}" != "true" ]]; then
            echo "❌ ERROR: Prebuild scripts have been modified but the required binaries have not been updated!"
            echo ""
            echo "The following files were changed in scripts/prebuild/:"
            echo "${{ steps.changed-files.outputs.all_changed_files }}"
            echo ""
            echo "Please ensure you have updated the following binaries:"
            echo "- scripts/prebuild-arm-mac-binary"
            echo "- scripts/prebuild-x64-linux-binary"
            echo ""
            echo "These binaries should be built from the updated prebuild scripts to ensure compatibility."
            exit 1

          else
            # Check if both binaries were updated
            ARM_MAC_UPDATED=false
            X64_LINUX_UPDATED=false

            if echo "${{ steps.check-binaries.outputs.all_changed_files }}" | grep -q "prebuild-arm-mac-binary"; then
              ARM_MAC_UPDATED=true
              echo "✅ ARM Mac binary updated"
            fi

            if echo "${{ steps.check-binaries.outputs.all_changed_files }}" | grep -q "prebuild-x64-linux-binary"; then
              X64_LINUX_UPDATED=true
              echo "✅ x64 Linux binary updated"
            fi

            if [[ "$ARM_MAC_UPDATED" != "true" || "$X64_LINUX_UPDATED" != "true" ]]; then
              echo "⚠️ WARNING: Not all required binaries were updated:"
              [[ "$ARM_MAC_UPDATED" != "true" ]] && echo "  - Missing: scripts/prebuild-arm-mac-binary"
              [[ "$X64_LINUX_UPDATED" != "true" ]] && echo "  - Missing: scripts/prebuild-x64-linux-binary"
              echo ""
              echo "Please ensure both binaries are updated when prebuild scripts change."
              exit 1
            fi
          fi

      - name: Success message
        if: steps.check-changes.outputs.prebuild_changed == 'false'
        run: |
          echo "✅ No prebuild script changes detected. No binary validation required."
