name: Compress Images

permissions:
  contents: write

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'content/**'

  workflow_dispatch:

jobs:
  compress-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "actions@github.com"

      - id: changed_image_files
        name: Get changed image files
        with:
          files: content/**/*.{png,jpg,jpeg,gif,svg}
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959 # v42.0.2


      - name: List all changed files
        if: steps.changed_image_files.outputs.any_changed == 'true'
        run: |
          echo "Changed image paths:"
          for file in ${{ steps.changed_image_files.outputs.all_changed_files }}; do
            echo "$file"
          done

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        if: steps.changed_image_files.outputs.any_changed == 'true'
        with:
          node-version-file: 'package.json'

      - name: Install Optimizt via npm
        if: steps.changed_image_files.outputs.any_changed == 'true'
        run: npm install --global @343dev/optimizt

      - name: Optimize images
        if: steps.changed_image_files.outputs.any_changed == 'true'
        run: optimizt --verbose ${{ steps.changed_image_files.outputs.all_changed_files }}

      - name: Commit optimized images
        if: steps.changed_image_files.outputs.any_changed == 'true'
        run: |
          git add -A
          git diff --quiet && git diff --staged --quiet \
            || git commit -m "Compress images"

      - name: Push changes
        if: steps.changed_image_files.outputs.any_changed == 'true'
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
